import Head from "next/head";
import styles from "@/styles/Home.module.css";
import axios from "axios";

export default function Home(props: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <ul>
            {props.activities.map((el: any, idx: any) => {
              return <li key={idx}>{el.title}</li>;
            })}
          </ul>
        </div>
      </main>
    </>
  );
}

const getData = async () => {
  const result = await axios.get("http://localhost:5000/api/activities");
  return result;
};

export async function getStaticProps() {
  const { data } = await getData();
  return {
    props: { activities: data },
    revalidate: 1,
  };
}
